# Generated by Django 3.1 on 2020-08-26 23:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_customer_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='image',
            new_name='profile_pic',
        ),
    ]
